[lint]
select = [
    "A",
    "ASYNC",
    "B",
    "BLE",
    "C4",
    "DTZ",
    "E",
    "EM",
    "F",
    "FLY",
    "G",
    "ISC",
    "ICN",
    "INT",
    "LOG",
    "N",
    "PIE",
    "PT",
    "PERF",
    "PLE0101",
    "PLR6301",
    "Q",
    "R",
    "RSE",
    "SLF",
    "SLOT",
    "SIM",
    "T10",
    "TRY",
    "TCH",
    "YTT",
    "W"
]
ignore = ["E501", "N999"]
preview = true
