site_name: Welcome to PyPDFForm - PyPDFForm Documentation
nav:
  - 'User Guide':
    - install.md
    - prepare.md
    - inspect.md
    - fill.md
    - style.md
    - draw.md
theme:
  name: readthedocs
  logo: img/logo.png
