site_name: Welcome to PyPDFForm - PyPDFForm Documentation
repo_url: https://github.com/chinapandaman/PyPDFForm/tree/master/docs
nav:
  - 'User Guide':
    - install.md
    - prepare.md
    - inspect.md
    - fill.md
    - style.md
    - draw.md
    - utils.md
theme:
  name: readthedocs
  logo: img/logo.png
