[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "PyPDFForm"
dynamic = ["version"]
description = "The Python library for PDF forms."
readme = "README.md"
authors = [
    {name = "Jinge Li"}
]
license = "MIT"
license-files = ["LICENSE"]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
requires-python = ">=3.8"
dependencies = [
    "cryptography",
    "pillow",
    "pypdf",
    "reportlab",
]

[project.urls]
Homepage = "https://github.com/chinapandaman/PyPDFForm"
Documentation = "https://chinapandaman.github.io/PyPDFForm/"

[project.optional-dependencies]
dev = [
    "coverage",
    "jsonschema",
    "mkdocs",
    "pudb",
    "pylint",
    "pyright",
    "pytest",
    "requests",
    "ruff",
]

[tool.coverage.run]
omit = [
    "venv/*",
    "tests/*",
]

[tool.setuptools.dynamic]
version = {attr = "PyPDFForm.__version__"}

[tool.setuptools.packages.find]
include = ["PyPDFForm"]
