name: Nightly Build

on:
  schedule:
    - cron: "00 00 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Set up environment
        run: |
          rm -rf PyPDFForm
          uv pip install PyPDFForm --system
          uv pip install -U -r pyproject.toml --extra dev --system
      - name: Run nightly tests
        run: |
          pytest
