name: Nightly Build

on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build dev image from latest tag
        run: |
          git checkout $(git describe --tags `git rev-list --tags --max-count=1`)
          docker build -t pypdfform-dev .
      - name: Run nightly tests on newest PDF samples
        run: |
          git checkout master
          docker exec -it $(docker run -it -d --rm -v ${PWD}/pdf_samples:/pypdfform/pdf_samples pypdfform-dev) pytest
